env:
  - IMGNAME=bradmorg/ubuntu:dbot

services:
  - docker

before_install:
- docker image build -t ${IMGNAME} .

script:
 - docker images


after_success:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
- docker push ${IMGNAME}
- echo "${SSH_KEY}" |  base64 --decode > /tmp/ssh_rsa
- chmod 600 /tmp/ssh_rsa
- ssh -o "StrictHostKeyChecking no" pi@${IPADDR} -i /tmp/ssh_rsa "docker run -d -e TOKEN=${TOKEN} ubuntu:dbot"